services:
  app:
    build:
      context: .
      args:
        - PUBLIC_CONVEX_URL=${PUBLIC_CONVEX_URL}
    ports:
      - '47823:3000'
    environment:
      - NODE_ENV=production
      - ORIGIN=http://localhost:47823
      - PUBLIC_CONVEX_URL=${PUBLIC_CONVEX_URL}
